---
- name: Ensure that /etc/rancher/rke2 exists
  ansible.builtin.file:
    name: /etc/rancher/rke2
    state: directory
    owner: root
    group: root

- name: Ensure that "{{ RKE_DATA_DIR }}" exists
  ansible.builtin.file:
    name: "{{ RKE_DATA_DIR }}"
    state: directory
    owner: root
    group: root

- name: Ensure that longhorn-storage exists
  ansible.builtin.file:
    name: "{{ RKE_LONGHORN_DIR }}"
    state: directory
    owner: root
    group: root
