---
- name: Configure initial RKE2 management master
  block:
    - name: run install script
      ansible.builtin.shell: >
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh - 

    - name: Copy /etc/rancher/rke2/config.yaml
      ansible.builtin.template:
        src: templates/rke_config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      register: config_copied

    - name: Ensure rke2-server service is started and enabled
      ansible.builtin.service:
        name: rke2-server
        enabled: yes

    - name: start and enable rke2-server service
      ansible.builtin.service:
        name: rke2-server
        state: started
        enabled: yes
    
    - name: copy kubeconfig to /tmp
      ansible.builtin.command: > 
        cp /etc/rancher/rke2/rke2.yaml /tmp/kubeconfig.yml

    - name: update kubeconfig
      ansible.builtin.lineinfile:
        path: /tmp/kubeconfig.yml
        regexp: 'server: https://127.0.0.1:6443'
        line: "    server: https://{{ RKE2_INITSERVER }}:6443"

    - name: fetch updated KUBECONFIG
      ansible.builtin.fetch:
        src: /tmp/kubeconfig.yml
        dest: ../kubeconfig
        flat: yes

  when: rke2_cluster_type == 'management' and rke2_node_type == 'cp_initial'
