---
- name: Post install on management servers
  block:
    - name: Find kubectl binary
      ansible.builtin.find:
        paths: "{{ RKE_DATA_DIR }}/data/"
        patterns: kubectl
        file_type: file
        recurse: true
      register: kubectl_files

    - name: Create symbolic link for kubectl
      file:
        src: "{{ kubectl_files.files[0].path }}"
        dest: /usr/local/bin/kubectl
        state: link
      when: kubectl_files.matched > 0

    - name: Add a line to ~/.bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export KUBECONFIG=/etc/rancher/rke2/rke2.yaml'
        state: present

    - name: install latest helm 
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  when: rke2_cluster_type == 'management'
