---
- name: After install of RKE2 cluster configure various components
  hosts: rke
  become: true
  
  tasks:
    - name: Charts configuration
      block:
        - name: install latest helm 
          ansible.builtin.shell: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

        - name: add certmanager helm chart
          ansible.builtin.shell: >
            helm repo add jetstack https://charts.jetstack.io --force-update
            helm upgrade -i cert-manager jetstack/cert-manager -n cert-manager --create-namespace --set crds.enabled=true
        
        - name: add rancher helm chart
          ansible.builtin.shell: >
            helm repo add rancher-latest https://releases.rancher.com/server-charts/latest --force-update
        
      when: rke2_cluster_type == 'management'
