---
- name: Uninstall rke2 service 
  hosts: all
  become: true
  
  tasks:
  - name: Stop rke2-server service
    ansible.builtin.service:
      name: rke2-server
      state: stopped
    ignore_errors: yes

  - name: Run the rke2-uninstall.sh command
    ansible.builtin.shell: >
      sh /usr/bin/rke2-uninstall.sh
    ignore_errors: yes

  - name: Remove /etc/rancher/rke2 directory
    ansible.builtin.file:
      name: /etc/rancher/rke2
      state: absent

  - name: Remove "{{ RKE_DATA_DIR }}" directory
    ansible.builtin.file:
      name: "{{ RKE_DATA_DIR }}"
      state: absent

  - name: Remove "{{ RKE_LONGHORN_DIR }}" directory
    ansible.builtin.file:
      name: "{{ RKE_LONGHORN_DIR }}"
      state: absent

  - name: Remove data-dir directory
    ansible.builtin.file:
      name: "{{ RKE_DATA_DIR }}"
      state: absent

  - name: Remove longhorn-dir directory
    ansible.builtin.file:
      name: "{{ RKE_LONGHORN_DIR }}"
      state: absent

  - name: Remove /usr/local/bin/helm
    ansible.builtin.file:
      name: /usr/local/bin/helm
      state: absent

  - name: Remove /usr/local/bin/kubectl
    ansible.builtin.file:
      name: /usr/local/bin/kubectl
      state: absent

  - name: Reboot the machine
    ansible.builtin.reboot:
      msg: "Rebooting the system"
      reboot_timeout: 600
